name = "OrthogonalPolynomialsQuasi"
uuid = "aa41a628-2c43-45df-899b-83ab96621781"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.2.1"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
InfiniteLinearAlgebra = "cde9dba0-b1de-11e9-2c62-0bab9446c55c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"

[compat]
ArrayLayouts = "0.4.5"
BandedMatrices = "0.15.11"
BlockArrays = "0.12.8"
BlockBandedMatrices = "0.9"
ContinuumArrays = "0.3"
DomainSets = "0.4, 0.5"
FastTransforms = "0.10.1"
FillArrays = "0.9.5"
HypergeometricFunctions = "0.3.2"
InfiniteArrays = "0.8"
InfiniteLinearAlgebra = "0.4.1"
IntervalSets = "0.3.1, 0.4, 0.5"
LazyArrays = "0.17.6"
QuasiArrays = "0.3.2"
julia = "1.5"

[extras]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
SemiseparableMatrices = "f8ebbe35-cbfb-4060-bf7f-b10e4670cf57"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "SemiseparableMatrices", "SpecialFunctions", "LazyBandedMatrices", "ArrayLayouts"]
