name = "OrthogonalPolynomialsQuasi"
uuid = "aa41a628-2c43-45df-899b-83ab96621781"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.1.3"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
InfiniteLinearAlgebra = "cde9dba0-b1de-11e9-2c62-0bab9446c55c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BandedMatrices = "0.15.11"
ContinuumArrays = "0.2.3"
DomainSets = "0.1, 0.2, 0.3, 0.4"
FastTransforms = "0.8, 0.9"
FillArrays = "0.8.10"
InfiniteArrays = "0.7.2"
InfiniteLinearAlgebra = "0.3.4"
IntervalSets = "0.3.1, 0.4, 0.5"
LazyArrays = "0.16.12"
QuasiArrays = "0.2.1"
julia = "1.3"

[extras]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
SemiseparableMatrices = "f8ebbe35-cbfb-4060-bf7f-b10e4670cf57"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff", "SemiseparableMatrices", "SpecialFunctions", "LazyBandedMatrices", "ArrayLayouts", "BlockArrays", "BlockBandedMatrices"]
